push_cube:
  available_data: ('state', 'sensor_data')
  sensor_data:
    data_source: 'base_camera'
    available_obs: ['rgb', 'depth', 'segmentation']

  store_shape:
    state: [35]
    rgb: [2, 128,128]
    depth: [2, 128,128]
    segmentation: [2, 128,128]